language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: clicker-react-2021
  api_key:
    secure: ZNl/XEWf/MwZ0XWO3MDgswsUPsZH8024hMgx1SwmkXyK56q7zY7kpC86Wop1r7RL/E6mg+O9r/mgb2EWWKRJKq0sdAypX9HzvM+Jr5W1QEyo8tbSkxKu4Hd0XWrQcBDIlWimDJa6sLG1YK9tUILkM212INQRMrlUYnqULJbdyqG8uMx6QJtDi1bjJZQY01z4AL+6MHUAtqDexezh72WnCcLoIIUK8JzMu10AOyixvNTOZxV6xpCUuFgDp+87020kto92CcZA9xXEktY9zJ4zWZ8JhP+tqi8lS09ZH4vqPkyz5BlBNoo6A7vAZFVXeLaAJDugW6ZGcqVXLR87/pf4jEEEaDqlj+l03vsjT9rOzl1/UgZg86x400BJYOyXDwC/SmXkhF93j9l7SlCU3q7/mUcm/nd0O2T1BXVM7XVdJ5Fs3T6uhDD7daNwXkMJeMpUSPjI9ygHgK5c1iGDGQ+xBagnf1nL8HEPiLCiNrrVEszh20yHhLbk8NEcWU0x97snnA21SGqIXcw+3gPViPV3SewZhLE6GXEg+RXPZitZKdFSXDZKuHrx17kDoBvlwxwbgxsgrHlNgWBr21oL4BvAANhwAO6F7GtVkhN/OzYKyTTSeMZ+iqEMswD+JW/VJxBN+xrLkfNc2QMjTGXUZKno4Wj6aslonx0hNIDt/TtAPC4=
